### ISSUE TITLE
Rename Status.FAILURE to Status.FAILED

### ISSUE THREAD

**Issue by anastasiosl** [SunRun/cfn-response-java#3]
Based on AWS documentation here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-responses.html

failure is signaled back to CloudFormation with a `Status` field of `FAILED`, not `FAILURE`.

**Comment by anastasiosl** [comment]
Took the liberty to submit the PR that addresses this.

**Comment by jhovell** [comment]
@anastasiosl I cut 1.0.2 release, if it shows up in Maven Central feel free to close this issue. Thanks again!

**Comment by alivogia** [comment]
Yup, I see it. Thank you.

**Comment by anastasiosl** [comment]
Yup, I see it. Thanks!
